fix: integration workflow
linode/packer-plugin-linode pull request #161
Opened 2023-11-27 18:57 UTC by ykim-1

## 📝 Description

Quick fix to the workflow yaml file to address recent build failures

## ✔️ How to Test

**How do I run the relevant unit/integration tests?**

## 📷 Preview

**If applicable, include a screenshot or code snippet of this change. Otherwise, please remove this section.**

2023-11-27 19:05 UTC, zliang-akamai commented on .github/workflows/go-test-multiplatform.yml
> +        uses: actions/upload-artifact@v2
Can we use v3?

2023-11-27 19:06 UTC, zliang-akamai commented on .github/workflows/go-test-multiplatform.yml
> +        uses: actions/download-artifact@v2
```suggestion
        uses: actions/download-artifact@v3
```

2023-11-27 19:09 UTC, zliang-akamai commented
The workflow looks very cool! Nice work!
<img width="974" alt="image" src="https://github.com/linode/packer-plugin-linode/assets/121905282/37f14e35-0578-4bfe-a4ee-cce189fe1e64">

2023-11-27 19:16 UTC, lgarber-akamai commented on .github/workflows/go-test-multiplatform.yml
> +  process-upload-report:
Could we ensure this only runs on pushed to `main` or `dev` since the OBJ secrets aren't accessible from PRs?

2023-11-27 19:16 UTC, lgarber-akamai requested changes
Looks good! Just one small thing

2023-11-27 19:16 UTC, lgarber-akamai commented on .github/workflows/go-test-multiplatform.yml
> +  process-upload-report:
Could we ensure this only runs on pushed to `main` or `dev` since the OBJ secrets aren't accessible from PR runs?

2023-11-27 20:05 UTC, ykim-1 commented on .github/workflows/go-test-multiplatform.yml
> +  process-upload-report:
Yup, we have code block below in the top level so all the jobs should be only running when there is push to dev or main

`  push:
    branches:
      - 'main'
      - 'dev'`

2023-11-27 22:23 UTC, ykim-1 commented
Apologies for many attempts, debugging on GHA is really frustrating... The workflow should be fixed with latest commit

2023-11-27 22:29 UTC, ykim-1 commented on .github/workflows/go-test-multiplatform.yml
> +  process-upload-report:
Also added an additional check in the job level - https://github.com/linode/packer-plugin-linode/actions/runs/7011334267

2023-11-27 23:40 UTC, zliang-akamai approved these changes

2023-11-27 23:40 UTC, zliang-akamai commented
Nice work!

2023-11-28 16:43 UTC, lgarber-akamai approved these changes
LGTM, thanks for addressing this!

2023-11-28 16:43 UTC, merged